# Generated by Django 6.1 on 2026-09-22 09:55

from django.db import migrations, models

# Eski (label-matn) qiymatlardan yangi barqaror machine-value'larga o'tkazish.
OLD_TO_NEW = {
    'Yangi xabar': 'message',
    "E'lon yoqtirildi": 'favorite',
    "E\u2019lon yoqtirildi": 'favorite',  # apostrof turli xil bo'lishi mumkin
    'Yangi sharh': 'review',
    'Moderatsiya natijasi': 'moderation',
    'Aksiya/chegirma': 'promo',
}
NEW_TO_OLD = {v: k for k, v in OLD_TO_NEW.items() if k in (
    'Yangi xabar', "E'lon yoqtirildi", 'Yangi sharh', 'Moderatsiya natijasi', 'Aksiya/chegirma',
)}


def migrate_labels_to_codes(apps, schema_editor):
    Notification = apps.get_model('users', 'Notification')
    for old_value, new_value in OLD_TO_NEW.items():
        Notification.objects.filter(notification_type=old_value).update(notification_type=new_value)


def migrate_codes_to_labels(apps, schema_editor):
    Notification = apps.get_model('users', 'Notification')
    for new_value, old_value in NEW_TO_OLD.items():
        Notification.objects.filter(notification_type=new_value).update(notification_type=old_value)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_review_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[('message', 'Yangi xabar'), ('favorite', "E'lon yoqtirildi"), ('review', 'Yangi sharh'),
                         ('moderation', 'Moderatsiya natijasi'), ('promo', 'Aksiya/chegirma')], max_length=20),
        ),
        migrations.RunPython(migrate_labels_to_codes, migrate_codes_to_labels),
    ]
